DS-2
girldevelopit/gdi-data-science pull request #2
Opened 2022-08-23 15:25 UTC by aszcoding

Added course content for Pandas class
Converted slideshow to most up to date reveal.js format
I named the folder intermediate-python-pandas because that's what it was named in the gdi-nyc repo
Added online resources to README.md for intro-sql course

2022-08-23 15:26 UTC, aszcoding commented
This PR is for Tinu's review

2022-08-23 18:58 UTC, tinuola commented
@aszcoding Thanks for the PR. I would just call the folder `pandas`.

2022-08-23 19:01 UTC, tinuola requested changes
Change folder name to just be "pandas". Thanks!

2022-08-24 01:43 UTC, tinuola approved these changes

2022-08-24 01:44 UTC, merged